spring:
#  sql:
#    init:
#        schema-locations: classpath*:db/h2/schema.sql #테스트용 테이블 생성
#        data-locations: classpath*:db/h2/data.sql #테스트용 데이터 삽입
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

## h2 database web?? ??
#spring.h2.console.enabled=true
#spring.datasource.generate-unique-name=false
#spring.h2.console.path=/h2-console
#
## spring - h2 ??
#spring.datasource.url = jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
##spring.datasource.url=jdbc:h2:~/spring-qna-db # embedded Mode : db ??? ?? ?? :  ~/spring-qna-db
##spring.datasource.url=jdbc:h2:mem:test # In-Memory mode
#spring.datasource.username=sa
#spring.datasource.password=
#
## jpa
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.generate-ddl=true
#spring.jpa.show-sql=true
#spring.jpa.database=h2
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
## logging
#logging.level.org.springframework.web=DEBUG
#logging.level.org.hibernate.sql=DEBUG
#logging.level.jpa=DEBUG
#
##spring.sql.init.mode=always
##spring.sql.init.schema-locations=classpath:schema.sql
##spring.sql.init.data-locations=classpath:data.sql
