INSERT INTO MEMBER (CREATED_AT, LAST_MODIFIED_AT, EMAIL, NAME, PASSWORD, MEMBER_ID) VALUES
(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'M1@GMAIL.COM', 'M1', 'MMM1111', DEFAULT),
(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'M2@GMAIL.COM', 'M2', 'MMM2222', DEFAULT);

INSERT INTO QUESTION (QUESTION_ID, CREATED_AT, LAST_MODIFIED_AT, QUESTION_BODY, QUESTION_TITLE, USER_ID) VALUES
(DEFAULT, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'HOW TO CALL REST API?', 'SPRING BOOT', 1),
(DEFAULT, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'HOW TO CALL REST API?', 'SPRING BOOT', 1),
(DEFAULT, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'HOW TO CALL REST API?', 'SPRING BOOT', 2),
(DEFAULT, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'HOW TO CALL REST API?', 'SPRING BOOT', 2);

INSERT INTO ANSWER (ANSWER_ID, CREATED_AT, LAST_MODIFIED_AT, ANSWER_BODY, MEMBER_ID, QUESTION_ID) VALUES
(DEFAULT, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'FIRST THING FIRST', 1, 1),
(DEFAULT, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'SECOND THING SECOND', 1, 1),
(DEFAULT, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'THIRD THING THIRD', 1, 1),
(DEFAULT, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'FORTH THING FORTH', 2, 1),
(DEFAULT, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'FIFTH THING FIFTH', 2, 1),
(DEFAULT, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'SIXTH THING SIXTH', 2, 1),
(DEFAULT, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'EIGHTH THING EIGHTH', 2, 1);